openapi: 3.0.0
info:
  title: Inventory & Dashboard API
  description: Dokumentasi API untuk sistem manajemen stok dan dashboard real-time
  version: 1.0.0
servers:
  - url: https://inventory-backend-portfolio-production.up.railway.app
    description: Production Server (railway)
  - url: http://localhost:3000
    description: Development servers

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      properties:
        sku:
          type: string
          example: "IPHONE-15-PRO"
        name:
          type: string
          example: "Iphone 15 Pro Max"
        stock:
          type: integer
          example: 50
        price:
          type: number
          example: 25000000
        threshold:
          type: integer
          example: 5

paths:
  # --- GROPU: AUTH ---
  /api/auth/register:
    post:
      summary: Daftar user baru (Admin)
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                username:
                  type: string
      responses:
        200:
          description: User berhasil dibuat

  /api/auth/login:
    post:
      summary: Login untuk mendapatkan Token JWT
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "admin@toko.com"
                password:
                  type: string
                  example: "admin123"
      responses:
        200:
          description: Login berhasil (Copy token dari sini)

  # --- GROUP: PRODUCTS ---
  /api/products:
    get:
      summary: Ambil semua data produk
      tags: [Products]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Halaman ke berapa
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Jumlah item per halaman
        - in: query
          name: search
          schema:
            type: string
          description: Cari berdasarkan nama produk (Opsional)
      responses:
        200:
          description: Berhasil mengambil data
    post:
      summary: Tambah produk baru
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: Produk berhasil dibuat

  # --- GROUP: TRANSACTIONS ---
  /api/transactions:
    get:
      summary: Ambil semua data transaksi
      tags: [Transactions]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Data Transactions Dashboard
    post:
      summary: Catat transaksi baru (Otomatis kurangi stok)
      tags: [Transactions]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                  example: 1
                quantity:
                  type: integer
                  example: 2
                platform:
                  type: string
                  example: "Tokopedia"
      responses:
        201:
          description: Transaksi sukses & Stok berkurang

  # --- GROUP: DASHBOARD ---
  /api/dashboard/stats:
    get:
      summary: Lihat ringkasan statistik (Omzet, Low Stock)
      tags: [Dashboard]
      responses:
        200:
          description: Data statistik dashboard
